# Generated by Django 3.0.6 on 2020-05-15 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='subject',
        ),
        migrations.AddField(
            model_name='book',
            name='subjects',
            field=models.ManyToManyField(help_text='Select a subject for this book', to='catalog.Subject'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this book across library', primary_key=True, serialize=False),
        ),
    ]
